### ISSUE TITLE
2.1. / 2.2 / 2.3 - Mercado Alvo, tendências de mercado e indústrias e perspectivas - anunciantes

### ISSUE THREAD

**Issue by carolmisorelli** [carolmisorelli/plan_taturana#2]
2.1. [Para que cliente/beneficiário você está criando valor?]

[Quem são os principais clientes-alvo? Qual a principal motivação dos clientes para comprarem seu produto/serviço? O que leva você a acreditar que há demanda suficiente para o seu produto/serviço? Além dos clientes-alvo, quem são os outros clientes potenciais? Quem são as pessoas dispostas a pagar por seu produto/serviço? Que tipo de relações cada um dos segmentos de clientes/ beneficiários espera ter e manter com vocês?]

2.2. [Você criou uma pesquisa para ajudá-lo a analisar o mercado? Quais são as tendências de mercado relevantes identificadas? Quais são as hipóteses para mudança? Quais são as oportunidades e como explorar as atuais circunstâncias?]

2.3. [Em que indústria o negócio irá funcionar? Quem são os concorrentes (número / tamanho / localização geográfica / etc.)? Eles são mesmo concorrentes ou são oportunidades de parceria? Será que você tem mesmo concorrentes? Quais são os seus pontos fortes e pontos fracos? Como você se diferenciar dos principais concorrentes? Alguma outra empresa recentemente entrou ou saiu desta indústria? Quem se beneficia do atual status quo? Há algum outro ponto de resistência para o seu negócio? Como o seu negócio será rentável e quais são as suas oportunidades de crescimento? Quais são os riscos que podem ocorrer quando você entrar no mercado? Como você descreveria o ambiente regulatório para esta atividade, neste sector? Quais são as oportunidades futuras relacionadas ao projeto que você pode já ter identificado (necessidades semelhantes identificado em outra região etc.)?]

**Comment by Alexandre-Taturana** [comment]
Falta revisão. As perguntas já estão respondidas

**Comment by carolmisorelli** [comment]
maravilha, ale! Falamos sobre na semana que vem, então! Quando puder, inicia o item 1? proposta e valor e descrição do serviço?

**Comment by carolmisorelli** [comment]
ficou bem legal, super interessante e traz vários elementos para pensarmos. fiz alguns comentários no texto, acho que o mais importante é entendermos melhor quem seriam esses clientes. que tipo de empresa anuncia hoje nos cinemas? está melhor explicado no próprio texto no drive.
